swiftradata:
  image: ubuntu
  volumes:
    - /app

swiftra:
  build: .
  volumes:
    - ./app:/code
  volumes_from:
    - swiftradata
  ports:
    - "8080:8080"
  command: bash -c "rm -rf /app/Sources 2> /dev/null ; cp Package.swift /app && cp -r Sources /app ; cd /app ; swift build; .build/debug/app"
