epochdata:
  image: ubuntu
  volumes:
    - /app

epochdb:
  image: postgres
  ports:
    - "5432:5432"

epoch:
  build: .
  volumes:
    - ./app:/code
  volumes_from:
    - epochdata
  links:
    - epochdb
  ports:
    - "8080:8080"
  command: bash -c "rm -rf /app/Sources 2> /dev/null ; cp Package.swift /app && cp -r Sources /app ; cd /app ; swift build && .build/debug/app"
